// UI/src/components/app/Login.vue
<template>
  <form
    @submit="onSubmit"
    style="width: 425px; margin: auto; padding-top: 10vh"
    class="center"
  >
    <md-card>
      <md-card-content>
        <h3>LOGIN</h3>
        <form action="">
          <md-field>
            <label>Email</label>
            <md-input v-model="username"></md-input>
          </md-field>
          <md-field>
            <label>Password</label>
            <md-input v-model="password" type="password"></md-input>
          </md-field>
        </form>
      </md-card-content>
      <md-card-actions style="border: 0px">
        <md-button :disabled="authLoading" type="submit" class="md-primary"
          >Login</md-button
        >
      </md-card-actions>
    </md-card>
  </form>
</template>

<script>
import { router } from "../../main";
import { mapGetters, mapActions } from "vuex";
export default {
  data: () => {
    return {
      username: "",
      password: "",
    };
  },
  computed: mapGetters(["authLoading"]),
  methods: {
    ...mapActions(["login"]),
    onSubmit(e) {
      e.preventDefault();
      this.login({
        email: this.username,
        password: this.password,
      }).catch((err) => {
        alert("Invalid email/password");
      });
    },
  },
};
</script>

<style>
</style>

// ui_react/src/app/Login.js
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Button, Card, Form, Grid, Icon, Message } from "semantic-ui-react";
import { history } from "..";
import { authLogin } from "../actions";
import { getToken } from "../helpers";

export const Login = () => {
  const [state, setState] = useState({
    email: "",
    password: "",
    invalidLogin: false,
  });

  const dispatch = useDispatch();
  const { loadingLogin } = useSelector((state) => state.auth);

  useEffect(() => {
    const token = getToken();
    if (token) {
      history.push("/dashboard");
    }
  }, []);

  const handleChange = (e) => {
    setState({ ...state, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setState({ ...state, invalidLogin: false });
    authLogin(
      {
        email: state.email,
        password: state.password,
      },
      dispatch
    ).catch((err) => {
      setState({ ...state, invalidLogin: true });
    });
  };

  return (
    <Grid container centered columns={2} style={{ marginTop: "2em" }}>
      <Grid.Column>
        <Card style={{ width: "100%" }}>
          <Card.Content header="Login" />
          <Card.Content>
            <Form id="form-login" onSubmit={handleSubmit}>
              <Form.Field>
                <label>Email</label>
                <input
                  placeholder="Email"
                  name="email"
                  value={state.email}
                  onChange={handleChange}
                ></input>
              </Form.Field>
              <Form.Field>
                <label>Password</label>
                <input
                  placeholder="Password"
                  type="password"
                  name="password"
                  value={state.password}
                  onChange={handleChange}
                ></input>
              </Form.Field>
              {state.invalidLogin && (
                <Message negative>
                  <p>Invalid email / password</p>
                </Message>
              )}
            </Form>
          </Card.Content>
          <Card.Content extra>
            <Button
              form="form-login"
              type="submit"
              disabled={loadingLogin}
              loading={loadingLogin}
              primary
              size="small"
              content="Log in"
            />
          </Card.Content>
        </Card>
      </Grid.Column>
    </Grid>
  );
};
